game1:
	gcc game1.c -o game1 -lraylib -lopengl32 -lgdi32 -lwinmm

game2:
	gcc game2.c -o game2 -lraylib -lopengl32 -lgdi32 -lwinmm

etu:
	gcc eatThemUp.c -o eatThemUp -lraylib -lopengl32 -lgdi32 -lwinmm